### PR TITLE
Let define syntax for extensions; Fix #6

### LINKED ISSUE #6: Let define syntax for extensions
E.g.

```
{
  ".css": "less",
  ".pcss": "scss"
}
```

It will be useful when I using PostCSS with some plugins, that extend CSS syntax. I use `postcss-nested` and get an error when try to csscomb the file:

``` less
.header
{
    color: #fff;
    background-color: $darkGray;

    .wrapper {
        display: flex;
        flex-direction: column;

        @media (--tablet)
        {
            flex-direction: row;
        }
    }
}
```

the error:

```
Please check the validity of the block starting from line #6

4 |     background-color: $darkGray;
6*|     .wrapper {
7 |         display: flex;
8 |         flex-direction: column;
```

### PR DESCRIPTION
**Pull request by isqua**
Discussion: #6 
In `.csscomb.json`:
```json
{
    "syntax": {
        ".css": "scss",
        ".lss": "less"
    }
}
```
If the implementation is ok, I’ll write tests.

### CODE REVIEW

**Comment by tonyganch** [comment]
Here: https://github.com/csscomb/core/blob/dev/src/core.js#L135
You want to use `_extractSyntax` in this place too.

**Comment by tonyganch** [comment]
> If the implementation is ok

It is. Thank you :elephant:

**Comment by isqua** [comment]
:up:

File: test/core.js [hunk 1]
```diff
@@ -24,10 +24,11 @@ describe('Core methods', function() {
     });
 
     it('should copy simple fields from config', function() {
-      var config = {lint: false, verbose: true};
+      var config = {lint: false, verbose: true, syntax: {}};
       comb.configure(config);
       assert.equal(comb.lint, config.lint);
       assert.equal(comb.verbose, config.verbose);
+      assert.equal(comb.syntaxMap, config.syntax);
```
Comment (tonyganch) [inline test/core.js]: You can't be sure that map was copied because `{}` is the default value it gets even if configuration fails.
I'd offer replacing on line 27 `syntax: {}` with `syntax: {'.css': 'scss'}`, for example.

Comment (isqua) [inline test/core.js]: `assert.equal` check pointers, not values:
```js
assert.equal({}, {}); // => false

let a = {};
let b = a;
assert.equal(a, b); // true
```

File: src/core.js [hunk 2]
```diff
@@ -37,6 +39,9 @@ class Comb {
         return new minimatch.Minimatch(pattern);
       });
 
+    if (config.syntax)
+      this.syntaxMap = config.syntax;
```
Comment (isqua) [inline src/core.js]: ... but may be `this.syntaxMap = util.extend({}, config.syntax)` would be better here?

File: test/core.js [hunk 3]
```diff
@@ -95,6 +96,15 @@ describe('Core methods', function() {
             done();
           });
     });
+
+    it('should use syntax from config', function(done) {
+      comb.use(require('./helpers/plugin_syntax_map'))
+        .configure({ syntax: { ".tcss": "scss" }})
```
Comment (tonyganch) [inline test/core.js]: Config should contain configuration for plugin.
For example:
```js
.configure({
  syntax: {
    '.tcss': 'scss'
  },
  'syntax-map': true
})
```
Otherwise plugin's `lint` method will not run.

Comment (isqua) [inline test/core.js]: fxd

File: test/core.js (hunk 1 above)
Comment (tonyganch) [inline test/core.js]: Good to know, thank you!

File: src/core.js (hunk 2 above)
Comment (tonyganch) [inline src/core.js]: I have no strong opinion on that one, so it's your call.

Comment (isqua) [inline src/core.js]: Wait a moment...

File: src/core.js [hunk 4]
```diff
@@ -21,6 +21,8 @@ class Comb {
     this.pluginsDependencies = {};
     // List of supported syntaxes.
     this.supportedSyntaxes = new Set();
+    // Mapping file extensions to syntax
+    this.syntaxMap = new Map();
```
Comment (isqua) [inline src/core.js]: Create a [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

File: src/core.js [hunk 5]
```diff
@@ -37,6 +39,12 @@ class Comb {
         return new minimatch.Minimatch(pattern);
       });
 
+    if (config.syntax) {
+      for (let key in config.syntax) {
+        this.syntaxMap.set(key, config.syntax[key]);
```
Comment (isqua) [inline src/core.js]: Add keys & values to it.

File: src/core.js [hunk 6]
```diff
@@ -391,6 +399,18 @@ class Comb {
...
+  /**
+   * Extract syntax by file path
+   *
+   * @param {String} path
+   * @returns {String} syntax
+   */
+  _extractSyntax(path) {
+    var extension = path.split('.').pop();
+
+    return this.syntaxMap.get('.' + extension) || extension;
```
Comment (isqua) [inline src/core.js]: Get values.

File: test/core.js [hunk 7]
```diff
@@ -38,6 +38,14 @@ describe('Core methods', function() {
       assert.deepEqual(comb.exclude, [minimatchedPattern]);
     });
 
+    it('should create syntax map', function() {
+      var config = {syntax: {'.css': 'scss'}};
+
+      comb.configure(config);
+      assert.equal(comb.syntaxMap.size, 1);
+      assert.equal(comb.syntaxMap.get('.css'), 'scss');
```
Comment (isqua) [inline test/core.js]: Check it size and values.

**Comment by isqua** [comment]
Is Map using ok? If so, I’ll squash commits.

**Comment by tonyganch** [comment]
Map is ok. Let me know when to merge.

**Comment by isqua** [comment]
It’s ready to merge now :fire:

**Comment by tonyganch** [comment]
Thank you very much :dancers:

**Comment by isqua** [comment]
When csscomb.js will support this feature?

**Comment by rodfersou** [comment]
I'm interested in this feature too
